export const ES_text = {
    empty_shopping_cart: 'El carrito de compras está vacío.',
    quantity: 'unidades',
    button_close: 'cerrar',
    button_buy: 'comprar',
    button_enter: 'ingresar',
    add_to_cart: 'añadir al carrito',
    price: 'precio',
    phone_modal: 'Por favor, ingrese su número de teléfono para continuar (Código de área, sin 0 +  Número de teléfono, sin 15).',
    add_address: 'Añade una dirección',
    delivery_address: 'Dirección de envío',
    select_home: 'Casa',
    select_work: 'Trabajo',
    select_other: 'Otro...',
    total:  'Total',
    save: 'guardar',
    receptor_input: 'Recibe:',
    please_log_in: 'Por favor ingrese con sus datos.',
    large_screen: 'Esta aplicación no está disponible en pantallas grandes por el momento.',
    please_select_address: 'Por favor ingrese un domicilio.',
    please_enter_name: 'Por favor ingrese un nombre'
}